-- 코드를 작성해주세요

SELECT 
    ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE, -- 노선별 총 누계거리
    CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),"km") AS AVERAGE_DISTANCE -- 노선별 평균 역 간 거리
FROM 
    SUBWAY_DISTANCE
GROUP BY 
    ROUTE
ORDER BY
    SUM(D_CUMULATIVE) DESC;