-- 코드를 작성해주세요
WITH YEARLY_MAX AS (
    SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (YM.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN YEARLY_MAX YM ON YEAR(DIFFERENTIATION_DATE) = YM.YEAR
ORDER BY YEAR ASC , YEAR_DEV ASC;
        